# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reactorctl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10reactorctl.proto\x12\x0bReactorCore\"=\n\x0c\x41\x63tiveStatus\x12-\n\x0b\x61\x63tiveState\x18\x01 \x01(\x0e\x32\x18.ReactorCore.ActiveState\"?\n\x0eSetActiveState\x12-\n\x0b\x61\x63tiveState\x18\x01 \x01(\x0e\x32\x18.ReactorCore.ActiveState\":\n\x0cRuleSettings\x12\x10\n\x08tickSize\x18\x01 \x01(\x04\x12\x18\n\x10minimumOrderSize\x18\x02 \x01(\x04\"}\n\nReactorCtl\x12\x35\n\x0esetActiveState\x18\x01 \x01(\x0b\x32\x1b.ReactorCore.SetActiveStateH\x00\x12\x31\n\x0cruleSettings\x18\x02 \x01(\x0b\x32\x19.ReactorCore.RuleSettingsH\x00\x42\x05\n\x03msg*5\n\x0b\x41\x63tiveState\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tSUSPENDED\x10\x01\x12\n\n\x06\x41\x43TIVE\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reactorctl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIVESTATE._serialized_start=348
  _ACTIVESTATE._serialized_end=401
  _ACTIVESTATUS._serialized_start=33
  _ACTIVESTATUS._serialized_end=94
  _SETACTIVESTATE._serialized_start=96
  _SETACTIVESTATE._serialized_end=159
  _RULESETTINGS._serialized_start=161
  _RULESETTINGS._serialized_end=219
  _REACTORCTL._serialized_start=221
  _REACTORCTL._serialized_end=346
# @@protoc_insertion_point(module_scope)
